services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile
      # This fixes the DNS issues during the 'apt-get' build phase
      network: host
    network_mode: host
    volumes:
      - /volume/docker-user/container-storage/rkllm/models:/app/models
    devices:
      - "/dev/rknn:/dev/rknn"
    restart: unless-stopped
    environment:
      - RUST_LOG=info

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      network: host
    network_mode: host
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
